# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-30 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=20, unique=True, verbose_name='英文名')),
                ('passwd', models.CharField(max_length=200, verbose_name='密码')),
                ('real_name', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('degree', models.CharField(choices=[('high school', '中专/高中'), ('undergraduate', '专科/本科'), ('master', '硕士研究生/硕士')], default='undergraduate', max_length=13, verbose_name='学历')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('height', models.CharField(max_length=3, verbose_name='身高')),
                ('weight', models.CharField(max_length=3, verbose_name='体重')),
                ('learning', models.CharField(max_length=200, verbose_name='学习经历')),
                ('allergies', models.CharField(max_length=200, verbose_name='过敏史')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
    ]
