# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-30 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(max_length=5, verbose_name='布置次数')),
                ('title', models.CharField(max_length=40, verbose_name='题目名称')),
                ('class_name', models.CharField(max_length=20, verbose_name='班级')),
                ('teacher', models.CharField(max_length=20, verbose_name='教师')),
                ('category', models.CharField(max_length=10, verbose_name='题目分类')),
                ('refer_complete_time', models.CharField(default='10', max_length=5, verbose_name='参考完成时间(分钟数)')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '面试作业布置',
                'verbose_name_plural': '面试作业布置',
            },
        ),
        migrations.CreateModel(
            name='InterviewCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('python', 'Python知识性题目'), ('algorithms', '算法题目')], default='python', max_length=10, verbose_name='题目分类')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '面试题目分类',
                'verbose_name_plural': '面试题目分类',
            },
        ),
        migrations.CreateModel(
            name='InterviewCorrecting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=20, verbose_name='学生')),
                ('question_answer', models.TextField(verbose_name='题目答案')),
                ('title', models.CharField(max_length=40, verbose_name='题目名称')),
                ('is_right', models.CharField(choices=[('1', '对'), ('0', '错')], default='0', max_length=1, verbose_name='对错')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('times', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interquestion.InterviewAssignment', verbose_name='布置次数')),
            ],
            options={
                'verbose_name': '面试作业批改',
                'verbose_name_plural': '面试作业批改',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='题目名称')),
                ('content', models.CharField(max_length=500, verbose_name='题目内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改时间')),
                ('category', models.ForeignKey(default='python', on_delete=django.db.models.deletion.CASCADE, to='Interquestion.InterviewCategory', verbose_name='题目分类')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '面试题库',
                'verbose_name_plural': '面试题库',
            },
        ),
        migrations.CreateModel(
            name='InterviewSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=20, verbose_name='学生')),
                ('submit_answer', models.TextField(verbose_name='作业答案')),
                ('title', models.CharField(max_length=40, verbose_name='题目名称')),
                ('is_done', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='完成')),
                ('complete_time', models.CharField(default='10', max_length=5, verbose_name='完成时间(分钟数)')),
                ('is_delete', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '面试作业提交',
                'verbose_name_plural': '面试作业提交',
            },
        ),
    ]
