# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-31 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interquestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewassignment',
            name='times',
        ),
        migrations.AddField(
            model_name='interviewsubmission',
            name='times',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Interquestion.InterviewAssignment', verbose_name='布置次数'),
        ),
    ]
