# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-02 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interquestion', '0002_auto_20180131_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewcorrecting',
            name='times',
        ),
        migrations.RemoveField(
            model_name='interviewsubmission',
            name='times',
        ),
    ]
