# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-02 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interquestion', '0003_auto_20180202_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewassignment',
            name='title',
            field=models.CharField(max_length=100, verbose_name='题目名称'),
        ),
        migrations.AlterField(
            model_name='interviewcorrecting',
            name='title',
            field=models.CharField(max_length=100, verbose_name='题目名称'),
        ),
        migrations.AlterField(
            model_name='interviewquestionbank',
            name='title',
            field=models.CharField(max_length=100, verbose_name='题目名称'),
        ),
        migrations.AlterField(
            model_name='interviewsubmission',
            name='title',
            field=models.CharField(max_length=100, verbose_name='题目名称'),
        ),
    ]
