# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-30 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='题目名称')),
                ('class_name', models.CharField(max_length=20, verbose_name='班级')),
                ('teacher', models.CharField(max_length=20, verbose_name='教师')),
                ('course', models.CharField(max_length=20, verbose_name='课程')),
                ('first_module', models.CharField(max_length=20, verbose_name='一级模块')),
                ('second_module', models.CharField(max_length=30, verbose_name='二级模块')),
                ('is_bonus', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='加分题')),
                ('refer_complete_time', models.CharField(default='10', max_length=5, verbose_name='参考完成时间(分钟数)')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作业布置',
                'verbose_name_plural': '作业布置',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=20, verbose_name='学生')),
                ('submit_answer', models.TextField(verbose_name='作业答案')),
                ('title', models.CharField(max_length=40, verbose_name='题目名称')),
                ('homework', models.FileField(upload_to='homework/%Y/%m/%d', verbose_name='上传作业')),
                ('is_done', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='完成')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
            },
        ),
    ]
