# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-02 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherupload',
            options={'verbose_name': '上传课件', 'verbose_name_plural': '上传课件'},
        ),
    ]
